changed exit codes in github terraform section

diff --git a/.github/workflows/build-staging-infrastructure.yml b/.github/workflows/build-staging-infrastructure.yml
--- a/.github/workflows/build-staging-infrastructure.yml
+++ b/.github/workflows/build-staging-infrastructure.yml
@@ -134,16 +134,16 @@ jobs:
               body: output
             })
 
-      - name: Check for Plan Failure
-        if: steps.plan.outputs.exitcode == 1
+      # - name: Check for Plan Failure
+      #   if: steps.plan.outputs.exitcode == 1
+      #   run: exit 1
+
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
         run: exit 1
 
-      #- name: Terraform Plan Status
-      #  if: steps.plan.outcome == 'failure'
-      #  run: exit 1
-
       - name: Terraform Apply
-        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        if: github.event_name == 'push' && steps.plan.outputs.exitcode == 2
+        #if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
+        #if: github.event_name == 'push' && steps.plan.outputs.exitcode == 2
         run: terraform apply -auto-approve -input=false
 
